# Generated by Django 5.1.4 on 2025-05-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_article_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
    ]
